services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drf_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./startup.sh:/app/startup.sh
      - ./wait-for-it.sh:/app/wait-for-it.sh
    env_file:
      - .env
    entrypoint: /app/startup.sh
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: drf_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: