# Generated by Django 5.1.5 on 2025-01-15 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu', models.IntegerField(default=1)),
                ('ram', models.IntegerField(default=1)),
                ('hdd', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('started', 'Started'), ('blocked', 'Blocked'), ('stopped', 'Stopped'), ('restarted', 'Restarted')], default='started', max_length=10)),
            ],
        ),
    ]
